### ISSUE TITLE
Android 版 Barcode 掃描效能

### ISSUE THREAD

**Issue by antyo** [g0v/victim#2]
手機型號：hTC one 801e、hTC one -E8
重演步驟：掃描時，掃描畫面反黑，且無法批次掃描，會退出APP畫面
問題描述：無法正常掃描

手機型號：Sony Z3、Sony Z5
重演步驟：掃描時，掃描畫面正常，但掃不出東西來
問題描述：無法正常掃描

手機型號：asus t100f、asus_T00G（Zenfone系列，社會局公務手機）
重演步驟：掃描時，掃描畫面變形，且速度緩慢
問題描述：掃描效能不佳

**Comment by gs0622** [comment]
Got program stopped while scanning barcode, device is engining sample no model name, post logcat log as below, for reference:

--------- beginning of crash
03-17 22:42:56.971  8699  8699 E AndroidRuntime: FATAL EXCEPTION: main
03-17 22:42:56.971  8699  8699 E AndroidRuntime: Process: g0v.victim, PID: 8699
03-17 22:42:56.971  8699  8699 E AndroidRuntime: java.lang.RuntimeException: getParameters failed (empty parameters)
03-17 22:42:56.971  8699  8699 E AndroidRuntime:    at android.hardware.Camera.native_getParameters(Native Method)
03-17 22:42:56.971  8699  8699 E AndroidRuntime:    at android.hardware.Camera.getParameters(Camera.java:1890)
03-17 22:42:56.971  8699  8699 E AndroidRuntime:    at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:88)
03-17 22:42:56.971  8699  8699 E AndroidRuntime:    at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1110)
03-17 22:42:56.971  8699  8699 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
03-17 22:42:56.971  8699  8699 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
03-17 22:42:56.971  8699  8699 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5446)
03-17 22:42:56.971  8699  8699 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
03-17 22:42:56.971  8699  8699 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:743)

**Comment by yutin1987** [comment]
@gs0622 Thank you very much, that like is a camera issue.
I will try https://github.com/lwansbrough/react-native-camera at weekend.

**Comment by kiang** [comment]
在小米的 HM NOTE 1W 手機上面是可以運行的

Android 版本 4.4.2 KOT49H
災民證版本 1.3.9

**Comment by kiang** [comment]
也許在 android 環境可以透過 react-native-send-intent 去呼叫 zxing 進行掃描( http://stackoverflow.com/questions/2050263/using-zxing-to-create-an-android-barcode-scanning-app )
